[variables]
# Disable NPM caching at the system/docker level to prevent bringing back broken binaries
NPM_CONFIG_CACHE = '/tmp/npm_cache_disabled'

[setup]
# Forzamos una versión de Node muy estable (20) donde este bug es menos agresivo
pkgs = ['nodejs_20']

[phases.install]
cmds = ['npm cache clean --force', 'rm -rf node_modules package-lock.json', 'npm install --include=optional']

[phases.build]
cmds = ['npm run build']
